class CppNativeSession:
    def __init__(
        self,
        schema_version: str,
        opcodes: tuple[int, ...],
        source_values: bytes,
        source_starts: bytes,
        source_ends: bytes,
        source_statuses: bytes,
        source_count: int,
        source_width: int,
        source_timebase_denominator: int,
        period_numerator: int,
        period_denominator: int,
        frame_size: int,
        frame_hop: int,
        kernel_abi: str,
        process_model: str,
        kernel_parameters: bytes,
        beam_count: int,
        weight_channel_count: int,
        collector_kind: int,
        collector_capacity: int,
        overflow_policy: int,
        source_node_id: int,
        rate_node_id: int,
        frame_node_id: int,
        map_node_id: int,
    ) -> None: ...
    def run(
        self,
    ) -> tuple[
        bytes,
        int,
        tuple[int, ...],
        tuple[int, ...],
        tuple[int, ...],
        tuple[int, ...],
        tuple[tuple[int, ...], ...],
        int,
        int,
        int,
        bool,
        tuple[int, int, int],
        tuple[int, int, int, int, int],
    ]: ...
